// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"api-template/internal/biz"
	"api-template/internal/conf"
	"api-template/internal/data"
	"api-template/internal/server"
	"api-template/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	clientRepo := data.NewClientRepo(dataData, logger)
	clientUseCase := biz.NewClientUseCase(clientRepo, logger)
	clientService := service.NewClientService(clientUseCase, logger)
	orderRepo := data.NewOrderRepo(dataData, logger)
	orderUseCase := biz.NewOrderUseCase(orderRepo, logger)
	orderService := service.NewOrderService(orderUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, clientService, orderService, logger)
	grpcServer := server.NewGRPCServer(confServer, clientService, orderService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
